version: "3.8"

services:
    app:
        build:
            context: .
            dockerfile: ./docker/publish.Dockerfile
            args:
                BUILD_CONFIGURATION: Debug
        stdin_open: true
        tty: true
