version: "3.8"

services:
    app:
        build:
            context: .
            dockerfile: ./docker/Dockerfile.release
        env_file:
            - .env
        stdin_open: true
        tty: true
