version: "3.8"

services:
    app:
        build:
            context: .
            dockerfile: ./src/docker/Dockerfile.debug
    tests:
        build:
            context: .
            dockerfile: ./tests/docker/Dockerfile.debug
        stdin_open: true
        tty: true
