version: "3.8"

services:
    app:
        build:
            context: .
            dockerfile: ./src/docker/Dockerfile.watch
        volumes:
            - ./src:/app
    tests:
        build:
            context: .
            dockerfile: ./tests/docker/Dockerfile.watch
        volumes:
            - ./tests:/aoc/tests
        stdin_open: true
        tty: true
