version: "3.8"

services:
    app:
        build:
            context: .
            dockerfile: ./src/docker/Dockerfile.release
        env_file:
            - ./src/.env
        stdin_open: true
        tty: true
