using System;
using App.Tasks.Year2021.Day24;
using Xunit;

namespace Tests.Tasks.Year2021.Day24
{
    public class Part2Tests
    {
        private readonly Part2 task;

        public Part2Tests()
        {
            task = new Part2();
        }

        [Fact]
        public void Solution_InstructionsExample_SmallestModelNumberAcceptedByMonadEquals()
        {
            string instructions = "inp w"
                + $"{Environment.NewLine}mul x 0"
                + $"{Environment.NewLine}add x z"
                + $"{Environment.NewLine}mod x 26"
                + $"{Environment.NewLine}div z 1"
                + $"{Environment.NewLine}add x 11"
                + $"{Environment.NewLine}eql x w"
                + $"{Environment.NewLine}eql x 0"
                + $"{Environment.NewLine}mul y 0"
                + $"{Environment.NewLine}add y 25"
                + $"{Environment.NewLine}mul y x"
                + $"{Environment.NewLine}add y 1"
                + $"{Environment.NewLine}mul z y"
                + $"{Environment.NewLine}mul y 0"
                + $"{Environment.NewLine}add y w"
                + $"{Environment.NewLine}add y 1"
                + $"{Environment.NewLine}mul y x"
                + $"{Environment.NewLine}add z y"
                + $"{Environment.NewLine}inp w"
                + $"{Environment.NewLine}mul x 0"
                + $"{Environment.NewLine}add x z"
                + $"{Environment.NewLine}mod x 26"
                + $"{Environment.NewLine}div z 1"
                + $"{Environment.NewLine}add x 11"
                + $"{Environment.NewLine}eql x w"
                + $"{Environment.NewLine}eql x 0"
                + $"{Environment.NewLine}mul y 0"
                + $"{Environment.NewLine}add y 25"
                + $"{Environment.NewLine}mul y x"
                + $"{Environment.NewLine}add y 1"
                + $"{Environment.NewLine}mul z y"
                + $"{Environment.NewLine}mul y 0"
                + $"{Environment.NewLine}add y w"
                + $"{Environment.NewLine}add y 11"
                + $"{Environment.NewLine}mul y x"
                + $"{Environment.NewLine}add z y"
                + $"{Environment.NewLine}inp w"
                + $"{Environment.NewLine}mul x 0"
                + $"{Environment.NewLine}add x z"
                + $"{Environment.NewLine}mod x 26"
                + $"{Environment.NewLine}div z 1"
                + $"{Environment.NewLine}add x 14"
                + $"{Environment.NewLine}eql x w"
                + $"{Environment.NewLine}eql x 0"
                + $"{Environment.NewLine}mul y 0"
                + $"{Environment.NewLine}add y 25"
                + $"{Environment.NewLine}mul y x"
                + $"{Environment.NewLine}add y 1"
                + $"{Environment.NewLine}mul z y"
                + $"{Environment.NewLine}mul y 0"
                + $"{Environment.NewLine}add y w"
                + $"{Environment.NewLine}add y 1"
                + $"{Environment.NewLine}mul y x"
                + $"{Environment.NewLine}add z y"
                + $"{Environment.NewLine}inp w"
                + $"{Environment.NewLine}mul x 0"
                + $"{Environment.NewLine}add x z"
                + $"{Environment.NewLine}mod x 26"
                + $"{Environment.NewLine}div z 1"
                + $"{Environment.NewLine}add x 11"
                + $"{Environment.NewLine}eql x w"
                + $"{Environment.NewLine}eql x 0"
                + $"{Environment.NewLine}mul y 0"
                + $"{Environment.NewLine}add y 25"
                + $"{Environment.NewLine}mul y x"
                + $"{Environment.NewLine}add y 1"
                + $"{Environment.NewLine}mul z y"
                + $"{Environment.NewLine}mul y 0"
                + $"{Environment.NewLine}add y w"
                + $"{Environment.NewLine}add y 11"
                + $"{Environment.NewLine}mul y x"
                + $"{Environment.NewLine}add z y"
                + $"{Environment.NewLine}inp w"
                + $"{Environment.NewLine}mul x 0"
                + $"{Environment.NewLine}add x z"
                + $"{Environment.NewLine}mod x 26"
                + $"{Environment.NewLine}div z 26"
                + $"{Environment.NewLine}add x -8"
                + $"{Environment.NewLine}eql x w"
                + $"{Environment.NewLine}eql x 0"
                + $"{Environment.NewLine}mul y 0"
                + $"{Environment.NewLine}add y 25"
                + $"{Environment.NewLine}mul y x"
                + $"{Environment.NewLine}add y 1"
                + $"{Environment.NewLine}mul z y"
                + $"{Environment.NewLine}mul y 0"
                + $"{Environment.NewLine}add y w"
                + $"{Environment.NewLine}add y 2"
                + $"{Environment.NewLine}mul y x"
                + $"{Environment.NewLine}add z y"
                + $"{Environment.NewLine}inp w"
                + $"{Environment.NewLine}mul x 0"
                + $"{Environment.NewLine}add x z"
                + $"{Environment.NewLine}mod x 26"
                + $"{Environment.NewLine}div z 26"
                + $"{Environment.NewLine}add x -5"
                + $"{Environment.NewLine}eql x w"
                + $"{Environment.NewLine}eql x 0"
                + $"{Environment.NewLine}mul y 0"
                + $"{Environment.NewLine}add y 25"
                + $"{Environment.NewLine}mul y x"
                + $"{Environment.NewLine}add y 1"
                + $"{Environment.NewLine}mul z y"
                + $"{Environment.NewLine}mul y 0"
                + $"{Environment.NewLine}add y w"
                + $"{Environment.NewLine}add y 9"
                + $"{Environment.NewLine}mul y x"
                + $"{Environment.NewLine}add z y"
                + $"{Environment.NewLine}inp w"
                + $"{Environment.NewLine}mul x 0"
                + $"{Environment.NewLine}add x z"
                + $"{Environment.NewLine}mod x 26"
                + $"{Environment.NewLine}div z 1"
                + $"{Environment.NewLine}add x 11"
                + $"{Environment.NewLine}eql x w"
                + $"{Environment.NewLine}eql x 0"
                + $"{Environment.NewLine}mul y 0"
                + $"{Environment.NewLine}add y 25"
                + $"{Environment.NewLine}mul y x"
                + $"{Environment.NewLine}add y 1"
                + $"{Environment.NewLine}mul z y"
                + $"{Environment.NewLine}mul y 0"
                + $"{Environment.NewLine}add y w"
                + $"{Environment.NewLine}add y 7"
                + $"{Environment.NewLine}mul y x"
                + $"{Environment.NewLine}add z y"
                + $"{Environment.NewLine}inp w"
                + $"{Environment.NewLine}mul x 0"
                + $"{Environment.NewLine}add x z"
                + $"{Environment.NewLine}mod x 26"
                + $"{Environment.NewLine}div z 26"
                + $"{Environment.NewLine}add x -13"
                + $"{Environment.NewLine}eql x w"
                + $"{Environment.NewLine}eql x 0"
                + $"{Environment.NewLine}mul y 0"
                + $"{Environment.NewLine}add y 25"
                + $"{Environment.NewLine}mul y x"
                + $"{Environment.NewLine}add y 1"
                + $"{Environment.NewLine}mul z y"
                + $"{Environment.NewLine}mul y 0"
                + $"{Environment.NewLine}add y w"
                + $"{Environment.NewLine}add y 11"
                + $"{Environment.NewLine}mul y x"
                + $"{Environment.NewLine}add z y"
                + $"{Environment.NewLine}inp w"
                + $"{Environment.NewLine}mul x 0"
                + $"{Environment.NewLine}add x z"
                + $"{Environment.NewLine}mod x 26"
                + $"{Environment.NewLine}div z 1"
                + $"{Environment.NewLine}add x 12"
                + $"{Environment.NewLine}eql x w"
                + $"{Environment.NewLine}eql x 0"
                + $"{Environment.NewLine}mul y 0"
                + $"{Environment.NewLine}add y 25"
                + $"{Environment.NewLine}mul y x"
                + $"{Environment.NewLine}add y 1"
                + $"{Environment.NewLine}mul z y"
                + $"{Environment.NewLine}mul y 0"
                + $"{Environment.NewLine}add y w"
                + $"{Environment.NewLine}add y 6"
                + $"{Environment.NewLine}mul y x"
                + $"{Environment.NewLine}add z y"
                + $"{Environment.NewLine}inp w"
                + $"{Environment.NewLine}mul x 0"
                + $"{Environment.NewLine}add x z"
                + $"{Environment.NewLine}mod x 26"
                + $"{Environment.NewLine}div z 26"
                + $"{Environment.NewLine}add x -1"
                + $"{Environment.NewLine}eql x w"
                + $"{Environment.NewLine}eql x 0"
                + $"{Environment.NewLine}mul y 0"
                + $"{Environment.NewLine}add y 25"
                + $"{Environment.NewLine}mul y x"
                + $"{Environment.NewLine}add y 1"
                + $"{Environment.NewLine}mul z y"
                + $"{Environment.NewLine}mul y 0"
                + $"{Environment.NewLine}add y w"
                + $"{Environment.NewLine}add y 15"
                + $"{Environment.NewLine}mul y x"
                + $"{Environment.NewLine}add z y"
                + $"{Environment.NewLine}inp w"
                + $"{Environment.NewLine}mul x 0"
                + $"{Environment.NewLine}add x z"
                + $"{Environment.NewLine}mod x 26"
                + $"{Environment.NewLine}div z 1"
                + $"{Environment.NewLine}add x 14"
                + $"{Environment.NewLine}eql x w"
                + $"{Environment.NewLine}eql x 0"
                + $"{Environment.NewLine}mul y 0"
                + $"{Environment.NewLine}add y 25"
                + $"{Environment.NewLine}mul y x"
                + $"{Environment.NewLine}add y 1"
                + $"{Environment.NewLine}mul z y"
                + $"{Environment.NewLine}mul y 0"
                + $"{Environment.NewLine}add y w"
                + $"{Environment.NewLine}add y 7"
                + $"{Environment.NewLine}mul y x"
                + $"{Environment.NewLine}add z y"
                + $"{Environment.NewLine}inp w"
                + $"{Environment.NewLine}mul x 0"
                + $"{Environment.NewLine}add x z"
                + $"{Environment.NewLine}mod x 26"
                + $"{Environment.NewLine}div z 26"
                + $"{Environment.NewLine}add x -5"
                + $"{Environment.NewLine}eql x w"
                + $"{Environment.NewLine}eql x 0"
                + $"{Environment.NewLine}mul y 0"
                + $"{Environment.NewLine}add y 25"
                + $"{Environment.NewLine}mul y x"
                + $"{Environment.NewLine}add y 1"
                + $"{Environment.NewLine}mul z y"
                + $"{Environment.NewLine}mul y 0"
                + $"{Environment.NewLine}add y w"
                + $"{Environment.NewLine}add y 1"
                + $"{Environment.NewLine}mul y x"
                + $"{Environment.NewLine}add z y"
                + $"{Environment.NewLine}inp w"
                + $"{Environment.NewLine}mul x 0"
                + $"{Environment.NewLine}add x z"
                + $"{Environment.NewLine}mod x 26"
                + $"{Environment.NewLine}div z 26"
                + $"{Environment.NewLine}add x -4"
                + $"{Environment.NewLine}eql x w"
                + $"{Environment.NewLine}eql x 0"
                + $"{Environment.NewLine}mul y 0"
                + $"{Environment.NewLine}add y 25"
                + $"{Environment.NewLine}mul y x"
                + $"{Environment.NewLine}add y 1"
                + $"{Environment.NewLine}mul z y"
                + $"{Environment.NewLine}mul y 0"
                + $"{Environment.NewLine}add y w"
                + $"{Environment.NewLine}add y 8"
                + $"{Environment.NewLine}mul y x"
                + $"{Environment.NewLine}add z y"
                + $"{Environment.NewLine}inp w"
                + $"{Environment.NewLine}mul x 0"
                + $"{Environment.NewLine}add x z"
                + $"{Environment.NewLine}mod x 26"
                + $"{Environment.NewLine}div z 26"
                + $"{Environment.NewLine}add x -8"
                + $"{Environment.NewLine}eql x w"
                + $"{Environment.NewLine}eql x 0"
                + $"{Environment.NewLine}mul y 0"
                + $"{Environment.NewLine}add y 25"
                + $"{Environment.NewLine}mul y x"
                + $"{Environment.NewLine}add y 1"
                + $"{Environment.NewLine}mul z y"
                + $"{Environment.NewLine}mul y 0"
                + $"{Environment.NewLine}add y w"
                + $"{Environment.NewLine}add y 6"
                + $"{Environment.NewLine}mul y x"
                + $"{Environment.NewLine}add z y";

            Assert.Equal(81514171161381, task.Solution(instructions));
        }
    }
}
