FROM mcr.microsoft.com/dotnet/core/sdk:3.1-buster AS sdk

# VSDBG debugger
RUN apt-get update \
    && apt-get install -y --no-install-recommends unzip \
    && curl -sSL https://aka.ms/getvsdbgsh | bash /dev/stdin -v latest -l /remote_debugger

WORKDIR /app

# Copy csproj and restore as distinct layers
COPY *.csproj ./
RUN dotnet restore

# Copy everything else and build
COPY . ./
RUN dotnet build
# ENTRYPOINT ["dotnet", "run"]
